#!/bin/sh

allow_download () {
    while [ 1 ]; do
        echo -n "Do you want this script to download all dependencies (y/n): "
        read input
        if [ $input == 'y' -o $input == 'Y' ]; then
            return
        elif [ $input == 'n' -o $input == 'N' ]; then
            echo "All depencies must be placed in the same directory as AquaPic.csproj"
            echo "Unable to build AquaPic application. Exiting"
            exit
        fi
    done
}

allow=0
if [ ! -f AquaPic/FileHelpers.dll ]; then
    echo "Dependency FileHelpers.dll not found"
    allow_download
    allow=1
    wget -O AquaPic/FileHelpers.dll "https://www.dropbox.com/s/385ljwkjq0960dv/FileHelpers.dll?dl=0" 
else
    echo "Dependecy FileHelpers.dll found"
fi

if [ ! -f AquaPic/CSScriptLibrary.dll ]; then
    echo "Dependency CSSriptLibrary.dll not found"
    if [ $allow -eq 0 ]; then
        allow_download
        allow=1
    fi
    wget -O AquaPic/CSScriptLibrary.dll "https://www.dropbox.com/s/sjm8rdrkaq1sf4v/CSScriptLibrary.dll?dl=0"
else
    echo "Dependency CSSriptLibrary.dll found"
fi

if [ ! -f AquaPic/Newtonsoft.Json.dll ]; then
    echo "Dependency Newtonsoft.Json.dll not found"
    if [ $allow -eq 0 ]; then
        allow_download
        allow=1
    fi
    wget -O AquaPic/Newtonsoft.Json.dll "https://www.dropbox.com/s/z2amvvkqy5t642x/Newtonsoft.Json.dll?dl=0"
else
    echo "Dependency Newtonsoft.Json.dll found"
fi

msbuild.exe /p:Configuration=Release AquaPic/AquaPic.csproj /m

#rm AquaPic/bin/Release/
