
// This file has been generated by the GUI designer. Do not modify.
namespace AquaPic
{
	public partial class powerWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AquaPic.powerWindow
			this.Name = "AquaPic.powerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("power");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 789;
			this.DefaultHeight = 551;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
