
// This file has been generated by the GUI designer. Do not modify.
namespace AquaPic
{
	public partial class mainWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AquaPic.mainWindow
			this.Name = "AquaPic.mainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("main");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
