
// This file has been generated by the GUI designer. Do not modify.
namespace MyWidgetLibrary
{
	public partial class MyLedWidget
	{
		private global::Gtk.DrawingArea area;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyWidgetLibrary.MyLedWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MyWidgetLibrary.MyLedWidget";
			// Container child MyWidgetLibrary.MyLedWidget.Gtk.Container+ContainerChild
			this.area = new global::Gtk.DrawingArea ();
			this.area.WidthRequest = 10;
			this.area.HeightRequest = 10;
			this.area.Name = "area";
			this.Add (this.area);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.area.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnAreaExposeEvent);
		}
	}
}
